### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/fluent/Request

### ISSUE THREAD

**Issue by cuizhennan** [luohaha/JLiteSpider#1]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/fluent/Request
    at extension.DefaultDownloader.download(DefaultDownloader.java:52)
    at core.Spider.begin(Spider.java:41)
    at htmlunit.JLiteSpider.main(JLiteSpider.java:15)

大神指点，这是什么情况？
httpclient 4.1.3
jsoup 1.8.3

**Comment by luohaha** [comment]
你的httpclient的版本太低了，在4.2版本后才支持fluent的api，所以他找不到`org/apache/http/client/fluent/Request`这个类。你可以直接导入我的jar包，里面打包了合适的httpclient。

**Comment by luohaha** [comment]
不好意思，我的jar包里没有打包httpclient，你可以去[这里](http://hc.apache.org/downloads.cgi)下载一个4.5版的httpclient

**Comment by cuizhennan** [comment]
多谢
